# Generated by Django 6.0 on 2025-12-27 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketingIntegration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Internal identifier", max_length=100),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("meta", "Meta Ads (Facebook/Instagram)"),
                            ("google_ads", "Google Ads"),
                            ("linkedin", "LinkedIn Ads"),
                            ("twitter", "X (Twitter) Ads"),
                            ("tiktok", "TikTok Ads"),
                            ("ott_generic", "OTT Player (Generic)"),
                            ("custom", "Custom Provider"),
                        ],
                        default="custom",
                        max_length=50,
                    ),
                ),
                (
                    "pixel_id",
                    models.CharField(
                        blank=True,
                        help_text="Pixel ID / Tracking ID / Container ID",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "access_token",
                    models.CharField(
                        blank=True,
                        help_text="API Access Token (for Server-Side API)",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "script_content",
                    models.TextField(
                        blank=True,
                        help_text="Custom Script/Tag Content (overrides automatic pixel injection)",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Marketing Integration",
                "verbose_name_plural": "Marketing Integrations",
            },
        ),
    ]
