# Generated by Django 6.0 on 2025-12-27 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0002_marketingintegration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marketingintegration",
            name="provider",
            field=models.CharField(
                choices=[
                    ("meta", "Meta Ads (Facebook/Instagram)"),
                    ("google_ads", "Google Ads"),
                    ("google_analytics", "Google Analytics"),
                    ("linkedin", "LinkedIn Ads"),
                    ("twitter", "X (Twitter) Ads"),
                    ("tiktok", "TikTok Ads"),
                    ("ott_generic", "OTT Player (Generic)"),
                    ("custom", "Custom Provider"),
                ],
                default="custom",
                max_length=50,
            ),
        ),
    ]
