# Generated by Django 6.0 on 2025-12-25 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autoscraper", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="scrapedjob",
            name="job_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="scrapedjob",
            name="salary_range",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="scrapedjob",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("expired", "Expired"),
                ],
                default="new",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="scrapedjob",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
