# Generated by Django 6.0 on 2025-12-25 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autoscraper", "0002_scrapedjob_job_type_scrapedjob_salary_range_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TargetCompany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("website", models.URLField(blank=True, null=True)),
                ("region", models.CharField(blank=True, max_length=255, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("last_scraped_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
