# Generated by Django 6.0 on 2025-12-26 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autoscraper", "0004_targetcompany_logo_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255, unique=True)),
                (
                    "domain",
                    models.CharField(
                        blank=True,
                        help_text="Company domain for logo fetch",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("logo_url", models.URLField(blank=True, max_length=500, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("website", models.URLField(blank=True, null=True)),
                ("logo_last_fetched", models.DateTimeField(blank=True, null=True)),
                (
                    "logo_fetch_failed",
                    models.BooleanField(
                        default=False, help_text="True if logo fetch failed"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Companies",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="scrapedjob",
            name="company_text",
            field=models.CharField(
                default="Unknown",
                help_text="Backup company name from scraper",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="scrapedjob",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="jobs",
                to="autoscraper.company",
            ),
        ),
    ]
