# Generated by Django 6.0 on 2025-12-26 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autoscraper", "0005_company_scrapedjob_company_text_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduledTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[("enrich_jobs", "Enrich Scraped Jobs")],
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "interval_minutes",
                    models.IntegerField(default=60, help_text="Run every X minutes"),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("next_run_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
