# Generated by Django 6.0 on 2025-12-27 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autoscraper", "0006_scheduledtask"),
        ("core", "0013_job_job_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="scrapedjob",
            name="job_role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="scraped_jobs",
                to="core.jobrole",
            ),
        ),
    ]
