# Generated by Django 6.0 on 2025-12-27 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "autoscraper",
            "0010_country_company_employee_count_company_founded_year_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="scheduledtask",
            name="name",
            field=models.CharField(
                choices=[
                    ("enrich_jobs", "Enrich Scraped Jobs"),
                    ("scrape_companies", "Scrape Target Companies"),
                    ("enrich_companies", "Enrich Company Profiles"),
                ],
                max_length=100,
                unique=True,
            ),
        ),
        migrations.CreateModel(
            name="CompanyCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Lucide icon name or emoji",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="autoscraper.companycategory",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Company Categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.AddField(
            model_name="company",
            name="categories",
            field=models.ManyToManyField(
                blank=True, related_name="companies", to="autoscraper.companycategory"
            ),
        ),
    ]
