# Generated by Django 6.0 on 2025-12-28 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autoscraper", "0014_companyscrapeprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="scrapedjob",
            name="dedup_hash",
            field=models.CharField(
                blank=True,
                help_text="hash(company_id + title + location)",
                max_length=64,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="scrapedjob",
            name="failure_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scrapedjob",
            name="last_attempt_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scrapedjob",
            name="retry_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="scrapedjob",
            name="scrape_status",
            field=models.CharField(
                choices=[
                    ("discovered", "Discovered"),
                    ("fetched", "Fetched"),
                    ("parsed_partial", "Parsed (Partial)"),
                    ("parsed_failed", "Parsed (Failed)"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="discovered",
                max_length=20,
            ),
        ),
    ]
