# Generated by Django 6.0 on 2025-12-25 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="auth_provider",
            field=models.CharField(
                default="email", help_text="e.g. Google, LinkedIn, Email", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="clerk_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_synced_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="subscription_plan",
            field=models.CharField(
                blank=True, default="Free Tier", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="subscription_status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("expired", "Expired"),
                    ("trial", "Trial"),
                ],
                default="inactive",
                max_length=20,
            ),
        ),
    ]
