# Generated by Django 6.0 on 2025-12-25 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_job"),
    ]

    operations = [
        migrations.CreateModel(
            name="APIConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_name",
                    models.CharField(
                        choices=[
                            ("serp", "SERP API (Google Jobs)"),
                            ("rapidapi", "RapidAPI (Active Jobs DB)"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("api_key", models.CharField(max_length=255)),
                (
                    "base_url",
                    models.URLField(
                        blank=True, help_text="Optional base URL override", null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "API Key Configuration",
                "verbose_name_plural": "API Key Configurations",
            },
        ),
    ]
