# Generated by Django 6.0 on 2025-12-25 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_apiconfiguration"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="apply_url",
            field=models.URLField(
                blank=True,
                help_text="External link for application (if applicable)",
                null=True,
            ),
        ),
    ]
