# Generated by Django 6.0 on 2025-12-25 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_job_apply_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="application_method",
            field=models.CharField(
                choices=[("external", "External URL"), ("internal", "On RemoteHive")],
                default="external",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="job_reference_id",
            field=models.CharField(
                blank=True,
                help_text="Unique Reference ID e.g., RH-1234",
                max_length=20,
                null=True,
                unique=True,
            ),
        ),
    ]
