# Generated by Django 6.0 on 2025-12-27 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_supportticket"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepageconfiguration",
            name="footer_address",
            field=models.CharField(default="San Francisco, CA", max_length=255),
        ),
        migrations.AddField(
            model_name="homepageconfiguration",
            name="footer_copyright",
            field=models.CharField(
                default="RemoteHive. All rights reserved.", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="homepageconfiguration",
            name="footer_description",
            field=models.TextField(
                default="Connecting talented professionals with remote opportunities worldwide."
            ),
        ),
        migrations.AddField(
            model_name="homepageconfiguration",
            name="footer_email",
            field=models.EmailField(default="support@remotehive.in", max_length=254),
        ),
        migrations.AddField(
            model_name="homepageconfiguration",
            name="footer_phone",
            field=models.CharField(default="+91-9667791765", max_length=20),
        ),
        migrations.CreateModel(
            name="FooterLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        choices=[
                            ("platform", "Platform"),
                            ("support", "Support"),
                            ("legal", "Legal"),
                            ("social", "Social Media"),
                        ],
                        default="platform",
                        max_length=20,
                    ),
                ),
                ("label", models.CharField(max_length=50)),
                (
                    "url",
                    models.CharField(
                        help_text="Relative path (e.g. /jobs) or full URL",
                        max_length=255,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="footer_links",
                        to="core.homepageconfiguration",
                    ),
                ),
            ],
            options={
                "ordering": ["section", "order"],
            },
        ),
    ]
