# Generated by Django 6.0 on 2025-12-27 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_job_job_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="SEOPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        help_text="URL Path e.g. / or /jobs",
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "keywords",
                    models.TextField(
                        blank=True, help_text="Comma separated keywords", null=True
                    ),
                ),
                (
                    "og_image",
                    models.URLField(
                        blank=True, help_text="OpenGraph Image URL", null=True
                    ),
                ),
                ("canonical_url", models.URLField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "SEO Page",
                "verbose_name_plural": "SEO Pages",
            },
        ),
        migrations.CreateModel(
            name="SEOTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Internal identifier e.g. GTM", max_length=100
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Full HTML tag e.g. <script>...</script>"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("head", "Head (<head>)"),
                            ("body_start", "Body Start (<body>)"),
                            ("body_end", "Body End (</body>)"),
                        ],
                        default="head",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Custom SEO Tag",
                "verbose_name_plural": "Custom SEO Tags",
                "ordering": ["location", "order"],
            },
        ),
    ]
