# Generated by Django 6.0 on 2025-12-28 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_apiconfiguration_extra_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobrole",
            name="employment_type",
            field=models.CharField(
                blank=True,
                help_text="e.g. Full-time, Contract",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="jobrole",
            name="kpis",
            field=models.TextField(
                blank=True, help_text="Key Performance Indicators", null=True
            ),
        ),
        migrations.AddField(
            model_name="jobrole",
            name="seniority_level",
            field=models.CharField(
                blank=True, help_text="e.g. Mid, Senior", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="jobrole",
            name="typical_skills",
            field=models.TextField(
                blank=True, help_text="Comma-separated skills", null=True
            ),
        ),
    ]
