# Generated by Django 6.0 on 2025-12-29 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_jobrole_remote_type_guidance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apiconfiguration",
            name="service_name",
            field=models.CharField(
                help_text="Service key like 'serp', 'rapidapi', 'linkedin', 'openwebninja', 'adzuna' or a custom value",
                max_length=50,
                unique=True,
            ),
        ),
    ]
