# Generated by Django 6.0 on 2025-12-26 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_job_application_method_job_job_reference_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apiconfiguration",
            name="service_name",
            field=models.CharField(
                help_text="Service key like 'serp', 'rapidapi', 'linkedin', or a custom value",
                max_length=50,
                unique=True,
            ),
        ),
    ]

