# Generated by Django 6.0 on 2025-12-26 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_apiconfiguration_service_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomePageConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "active_jobs_count",
                    models.CharField(
                        default="10k+", help_text="e.g. 10k+", max_length=20
                    ),
                ),
                (
                    "companies_count",
                    models.CharField(
                        default="2.5k", help_text="e.g. 2.5k", max_length=20
                    ),
                ),
                (
                    "success_rate",
                    models.CharField(
                        default="95%", help_text="e.g. 95%", max_length=20
                    ),
                ),
                (
                    "countries_count",
                    models.CharField(
                        default="50+", help_text="e.g. 50+", max_length=20
                    ),
                ),
                (
                    "hero_title",
                    models.CharField(
                        default="Find Your Dream Remote Job", max_length=255
                    ),
                ),
                (
                    "hero_subtitle",
                    models.TextField(
                        default="Connect with top companies offering remote opportunities worldwide."
                    ),
                ),
                (
                    "search_placeholder",
                    models.CharField(default="Job title or keyword", max_length=100),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Home Page Configuration",
                "verbose_name_plural": "Home Page Configuration",
            },
        ),
    ]
