# Generated by Django 6.0 on 2025-12-27 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_homepageconfiguration"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomePageRegion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Display Name e.g. United States", max_length=50
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        help_text="Filter Value e.g. United States", max_length=50
                    ),
                ),
                (
                    "icon_emoji",
                    models.CharField(help_text="Emoji Flag e.g. 🇺🇸", max_length=10),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="regions",
                        to="core.homepageconfiguration",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="HomePageRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Display Name e.g. Engineering", max_length=50
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        help_text="Filter Value e.g. engineering", max_length=50
                    ),
                ),
                (
                    "icon_name",
                    models.CharField(
                        help_text="Lucide Icon Name e.g. Code2, Briefcase",
                        max_length=50,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles",
                        to="core.homepageconfiguration",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
