# Generated by Django 6.0 on 2025-12-27 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_homepageconfiguration_footer_address_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobFamily",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Job Families",
                "ordering": ["order", "name"],
            },
        ),
        migrations.AlterField(
            model_name="apiconfiguration",
            name="service_name",
            field=models.CharField(
                help_text="Service key like 'serp', 'rapidapi', 'linkedin', 'openwebninja' or a custom value",
                max_length=50,
                unique=True,
            ),
        ),
        migrations.CreateModel(
            name="JobCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="core.jobfamily",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Job Categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="JobRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("is_remote_friendly", models.BooleanField(default=False)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles",
                        to="core.jobcategory",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Job Roles",
                "ordering": ["name"],
            },
        ),
    ]
