# Generated by Django 6.0 on 2025-12-27 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_jobfamily_alter_apiconfiguration_service_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="job_role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="jobs",
                to="core.jobrole",
            ),
        ),
    ]
