# Generated by Django 6.0 on 2025-12-28 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_seopage_seotag"),
    ]

    operations = [
        migrations.AddField(
            model_name="apiconfiguration",
            name="extra_config",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Additional JSON config (e.g. {'cx': '...'})",
                null=True,
            ),
        ),
    ]
