# Generated by Django 6.0 on 2025-12-28 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_jobrole_employment_type_jobrole_kpis_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobrole",
            name="remote_type_guidance",
            field=models.CharField(
                blank=True,
                help_text="e.g. Fully remote, Remote-first",
                max_length=100,
                null=True,
            ),
        ),
    ]
