# Generated by Django 6.0 on 2025-12-25 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autoscraper", "0003_targetcompany"),
    ]

    operations = [
        migrations.AddField(
            model_name="targetcompany",
            name="logo_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
