# Generated by Django 6.0 on 2025-12-27 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autoscraper", "0007_scrapedjob_job_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduledtask",
            name="target_companies",
            field=models.ManyToManyField(
                blank=True,
                help_text="Select companies to scrape for this task",
                to="autoscraper.company",
            ),
        ),
        migrations.AlterField(
            model_name="scheduledtask",
            name="name",
            field=models.CharField(
                choices=[
                    ("enrich_jobs", "Enrich Scraped Jobs"),
                    ("scrape_companies", "Scrape Target Companies"),
                ],
                max_length=100,
                unique=True,
            ),
        ),
        migrations.CreateModel(
            name="ScraperLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField(auto_now_add=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("stopped", "Stopped"),
                        ],
                        default="running",
                        max_length=20,
                    ),
                ),
                ("total_companies_target", models.IntegerField(default=0)),
                ("companies_processed", models.IntegerField(default=0)),
                ("jobs_found", models.IntegerField(default=0)),
                (
                    "current_company",
                    models.CharField(
                        blank=True,
                        help_text="Currently scraping...",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("message", models.TextField(blank=True, null=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="autoscraper.scheduledtask",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_time"],
            },
        ),
    ]
