# Generated by Django 6.0 on 2025-12-27 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autoscraper", "0008_scheduledtask_target_companies_and_more"),
        ("core", "0013_job_job_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduledtask",
            name="target_job_roles",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific roles to target (empty = all)",
                to="core.jobrole",
            ),
        ),
    ]
