# Generated by Django 6.0 on 2025-12-28 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autoscraper", "0011_alter_scheduledtask_name_companycategory_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scrapedjob",
            name="apply_url",
            field=models.URLField(
                blank=True,
                help_text="Direct application link if different from source URL",
                max_length=500,
                null=True,
            ),
        ),
    ]
