# Generated by Django 6.0 on 2025-12-28 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autoscraper", "0012_scrapedjob_apply_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="scrapedjob",
            name="experience",
            field=models.CharField(
                blank=True, help_text="e.g. 3-5 years", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="scrapedjob",
            name="requirements",
            field=models.TextField(blank=True, null=True),
        ),
    ]
