# Generated by Django 6.0 on 2025-12-28 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autoscraper", "0013_scrapedjob_experience_scrapedjob_requirements"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyScrapeProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "allowed_domains",
                    models.JSONField(
                        default=list,
                        help_text="List of strict allowed domains/subdomains (e.g. ['careers.airbnb.com', 'airbnb.com'])",
                    ),
                ),
                (
                    "discovery_strategy",
                    models.CharField(
                        choices=[
                            (
                                "google_site_search",
                                "Google Site Search (site:domain.com)",
                            ),
                            ("career_page_crawl", "Career Page Crawl (Recursive)"),
                            ("sitemap_xml", "Sitemap.xml Parsing"),
                            ("ats_direct", "Known ATS Direct Path"),
                        ],
                        default="google_site_search",
                        max_length=50,
                    ),
                ),
                (
                    "ats_root_url",
                    models.URLField(
                        blank=True,
                        help_text="Direct URL to ATS if using ats_direct strategy",
                        null=True,
                    ),
                ),
                (
                    "render_required",
                    models.BooleanField(
                        default=False,
                        help_text="Use Selenium/Playwright? (Slower, Costlier)",
                    ),
                ),
                ("scrape_frequency_hours", models.IntegerField(default=24)),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("last_status", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "company",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scrape_profile",
                        to="autoscraper.company",
                    ),
                ),
            ],
        ),
    ]
